language: node_js
node_js:
   - "node"
cache:
  directories:
    - node_modules
script:
  - npm install
  - npm run build

deploy:
  provider: releases
  api_key: $OAUTH_TOKEN
  file: dist/*
  skip_cleanup: true
  on:
    branch: master
